# Generated by Django 3.0.2 on 2020-03-05 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legends',
            old_name='L_Twitter',
            new_name='L_Instagram',
        ),
        migrations.AddField(
            model_name='education',
            name='E_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='WE_companyName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
